### ISSUE TITLE
Fog rendering problems in xash3d on remote

### ISSUE THREAD

**Issue by mittorn** [lunixbochs/glshim#125]
glFogv used
![xash3d-fog1](https://cloud.githubusercontent.com/assets/2101109/9022137/a9010236-388a-11e5-8860-b0c84ed46ae4.png)

**Comment by lunixbochs** [comment]
glFogv is an easy fix. I don't forward the pointer yet.

**Comment by lunixbochs** [comment]
Should be fixed by 0dd56fc7431c11a220985fb5ef4384c83443ecb5
