### ISSUE TITLE
epoxy_glx_version: Assertion `ret == 2' failed.

### ISSUE THREAD

**Issue by ruleh** [lunixbochs/glshim#148]
I compiled (x86_64) and installed glshim and glu.
Aftter a syatem update, I got the following error message when trying to run firefox 43 (42 works just fine) or winetricks (not sure if it worked before or not).
"dispatch_glx.c:61: epoxy_glx_version: Assertion `ret == 2' failed."
Any idea why or how?

**Comment by lunixbochs** [comment]
What x86_64 platform do you have that needs glshim? Also, glshim does not yet officially support WINE.

**Comment by ruleh** [comment]
I use an Asus Zenfone 2 z551ml.l which uses android (and gles)
Also I didn't mean running win aplications using wine, just the gui of winetricks doesn't load.
Similarly, firefox would also not load any gui (or anything at all)

**Comment by lunixbochs** [comment]
As far as I know WINE doesn't use libepoxy, so I have no idea what you're doing here.

winetricks uses the WINE UI as far as I know, and glshim does not support WINE. You might want to make sure your WINE has GDI set to not use OpenGL.
