### ISSUE TITLE
maemo: quitting/ending causes egl-errors

### ISSUE THREAD

**Issue by aapo** [lunixbochs/glshim#15]
Maemo5/N900

Every time I quit or end application, or it crashes it gives:

    ERROR: EGL Error detected: EGL_BAD_NATIVE_WINDOW (0x300B)
    ERROR: EGL Error detected: EGL_BAD_MATCH (0x3009)

Is this happening on other devices too?

**Comment by lunixbochs** [comment]
I haven't seen any issues like this in a long time. Reopen if you're still having problems.
