### ISSUE TITLE
Some problem while Compile in x86 Linux environment (ExaGear)

### ISSUE THREAD

**Issue by AllPlatform** [lunixbochs/glshim#177]
`root@localhost:~/glshim/build#` cmake ..                 
-- The C compiler identification is GNU 4.8.2           
-- The CXX compiler identification is GNU 4.8.2         
-- Check for working C compiler: /usr/bin/cc            
-- Check for working C compiler: /usr/bin/cc -- works   
-- Detecting C compiler ABI info                        
-- Detecting C compiler ABI info - done                 
-- Check for working CXX compiler: /usr/bin/c++         
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info                      
-- Detecting CXX compiler ABI info - done               
-- Configuring done                                     
-- Generating done                                      
-- Build files have been written to: /root/glshim/build
`root@localhost:~/glshim/build# uname -a`
Linux localhost 3.18.120-perf-gd85b39b #1 SMP PREEMPT Fri May 8 17:16:24 CST 2020 i686 i686 i686 GNU/Linux      
root@localhost:~/glshim/build# make
Scanning dependencies of target GL_obj
`[  2%] Building C object src/CMakeFiles/GL_obj.dir/gl/wrap/stub.c.o`
In file included 

                 from /root/glshim/src/gl/wrap/../../util/vectorial/simd4f.h:20:0, 
                 from /root/glshim/src/gl/wrap/../../util/mat4.h:4,
                 from /root/glshim/src/gl/wrap/../types.h:13,
                 from /root/glshim/src/gl/wrap/glpack.h:1,
                 from /root/glshim/src/gl/wrap/stub.h:2,
                 from /root/glshim/src/gl/wrap/stub.c:2:

/root/glshim/src/gl/wrap/../../util/vectorial/simd4f_gnu.h: In function ‘simd4f_create’:
/root/glshim/src/gl/wrap/../../util/vectorial/simd4f_gnu.h:31:1: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
 vectorial_inline simd4f simd4f_create(float x, float y, float z, float w) {
 ^
`[  5%] Building C object src/CMakeFiles/GL_obj.dir/gl/wrap/gl.c.o`

Pls help

**Comment by lunixbochs** [comment]
Sorry, I’m not providing user-facing support for this project right now. Feel free to submit a pull request.

**Comment by AllPlatform** [comment]
I just want to use the OpenGL remote from glshim for ExaGear

**Comment by Malaska678** [comment]
> I just want to use the OpenGL remote from glshim for ExaGear

@AllPlatform Use gl4es?

**Comment by lunixbochs** [comment]
gl4es is not the same project as glshim anymore, as ptitseb never integrated my improvements / remote rendering and never upstreamed any fixes. gl4es does not support remote rendering or my software renderer, see the following links:

- https://github.com/ptitSeb/gl4es/issues/6
> Just to mention, gl4es cannot be used with Exagear (or QEMU), as I never implemented the "proxy" mode that lunixbochs developped in glshim (and it was never my intension to do so, as I had other ideas in mind for 3D acceleration in emulation).
- https://pyra-handheld.com/boards/threads/exagear-is-dead.83548/page-4

You could use gl4es with box86 instead of exagear though.

**Comment by Malaska678** [comment]
Ah ok

**Comment by Malaska678** [comment]
> gl4es is not the same project as glshim anymore, as ptitseb never integrated my improvements / remote rendering and never upstreamed any fixes. gl4es does not support remote rendering or my software renderer, see the following links:
> 
> * [ptitSeb/gl4es#6](https://github.com/ptitSeb/gl4es/issues/6)
> 
> > Just to mention, gl4es cannot be used with Exagear (or QEMU), as I never implemented the "proxy" mode that lunixbochs developped in glshim (and it was never my intension to do so, as I had other ideas in mind for 3D acceleration in emulation).
> 
> * https://pyra-handheld.com/boards/threads/exagear-is-dead.83548/page-4
> 
> You could use gl4es with box86 instead of exagear though.
+Use Wine?

**Comment by Malaska678** [comment]
@lunixbochs ?

**Comment by Malaska678** [comment]
> gl4es is not the same project as glshim anymore, as ptitseb never integrated my improvements / remote rendering and never upstreamed any fixes. gl4es does not support remote rendering or my software renderer, see the following links:
> 
> * [ptitSeb/gl4es#6](https://github.com/ptitSeb/gl4es/issues/6)
> 
> > Just to mention, gl4es cannot be used with Exagear (or QEMU), as I never implemented the "proxy" mode that lunixbochs developped in glshim (and it was never my intension to do so, as I had other ideas in mind for 3D acceleration in emulation).
> 
> * https://pyra-handheld.com/boards/threads/exagear-is-dead.83548/page-4
> 
> You could use gl4es with box86 instead of exagear though.

@lunixbochs Then use it with wine?

**Comment by AllPlatform** [comment]
@Malaska678 
gl4es It is very hard to use on Android and I also have no idea, In java it is very difficult to call functions from java  or android uses only OpenGL ES so there is no statement calling OpenGL,  To use the gl4es library ptitSeb suggested using the native code SDL and I'm not good at C and java either

**Comment by AllPlatform** [comment]
![1](https://user-images.githubusercontent.com/44525248/95662762-7bb41780-0b63-11eb-9e54-df22293dcd4a.png)


I used to think it like this but it's really difficult it need call JNI function from a method in C

**Comment by Malaska678** [comment]
U call yourself bad but look at me. I can only create simple calculator 3 nums only so im way more bad

**Comment by mittorn** [comment]
last released exagear versions has some loader support (it seems can load ld-linux), so it is potentially possible to implement faster proxy for gl4es

**Comment by AllPlatform** [comment]
@mittorn 
Is it like this? 
`LD_LIBRARY_PATH=/PATH/TO/LibGL.so libubt`
i don't know how to make exagear Windows emulator recognize libGL.so file

**Comment by mittorn** [comment]
No, it will not work as is. And we do not have any docs for it, but it seems to possible to implement some proxy using it

**Comment by SavagePy10** [comment]
I just realized im talking to akira yuki

**Comment by SavagePy10** [comment]
My messages are too cringy... Im still not a programmer btw but i understand now...
