### ISSUE TITLE
detect the raspberry Pi at runtime instead of requiring a different build

### ISSUE THREAD

**Issue by lunixbochs** [lunixbochs/glshim#55]

**Comment by kika123** [comment]
bcm_host_init is only needed when using DispManX.You can try copying image data to an X11 buffer( if EGL_VENDOR=Broadcom)

**Comment by lunixbochs** [comment]
Do you have a link on this?

**Comment by kika123** [comment]
I don't have an exact link, but I use that in my code and it works. (now migrated to Mesa, so I don't need to use a BCM driver any more). I thing you can try loading libEGL and dlsym() at runtime to see if there is bcm_host_init()

**Comment by kika123** [comment]
if you need DispManX

**Comment by lunixbochs** [comment]
partly done in 027839f2c9c2a64d75eaa694699c196e363e9b95

looks like rpi link target still needs to be different though
