### ISSUE TITLE
EGL_NOT_INITIALIZED (0x3001)

### ISSUE THREAD

**Issue by jzemeocala** [lunixbochs/glshim#61]
Hello lunixbochs,
First off, I would like to say how much I appreciate your hard work with this code.
I was able to get glshim running perfectly fine on the pi but I have recently switched to using a cubieboard2 for development and regardless of what OS i run (mostly debian and ubuntu based ones) and what dependencies I install, I have been unable to get glshim to work.

It compiles fine but with no issues but when I try to test glxgears with it I recieve the error in the title of this post.

any help would be greatly appreciated

**Comment by kika123** [comment]
It is not working on my tablet (Kurio 7S, Cubian X,Allwinner A20)
with the same error

**Comment by ssvb** [comment]
@kika123 does a basic triangle test work? if no, then this is not a glshim issue.

**Comment by kika123** [comment]
with EGL_BAD_NATIVE_WINDOW err
but es2gears works.

**Comment by kika123** [comment]
Chromium also does not work, but es2tri, glmark2-es2 are working

**Comment by kika123** [comment]
@ssvb mali blobs are not working with most of the apps (r3p0) Should r3p2 make things better?

**Comment by kika123** [comment]
ptitSeb's repo is working but with *weird* artifacts. es2gears is in grey and not all the gears are seen at a time

**Comment by lunixbochs** [comment]
glshim isn't for es2 applications, which should already run on your target. It's for GL applications, like glxgears. You need a working es1 driver for glshim to work.

**Comment by kika123** [comment]
@lunixbochs I know. seandepagnier's GLshim fork is working.
But not the original project
