### ISSUE TITLE
typo in src/gl/wrap/gles2.h ES2 branch

### ISSUE THREAD

**Issue by meveric** [lunixbochs/glshim#75]
31546: 
#define glShaderSourceARB_ARG_EXPAND GLhandleARB shaderObj, GLsizei count, const GLcharARB ** string, const GLint * lengths

should be

#define glShaderSourceARB_ARG_EXPAND GLhandleARB shaderObj, GLsizei count, const GLcharARB * string, const GLint * lengths

you kinda added a second * before the string.. that breaks the build for ES2 with
error: conflicting types for ‘glShaderSourceARB’

**Comment by lunixbochs** [comment]
Wrong. Take a look in the `glext.h` header.

`GLAPI void APIENTRY glShaderSourceARB (GLhandleARB shaderObj, GLsizei count, const GLcharARB* *string, const GLint *length);`

Particularly `const GLcharARB* *string`. The change was correct. Anyway, the ES2 public stuff isn't really for people to use. There are probably changes I haven't pushed yet. The only thing working with it right now are programs that already supported ES2.
