### ISSUE TITLE
glXDestroyPbuffer

### ISSUE THREAD

**Issue by krnlyng** [lunixbochs/glshim#90]
Hi!
i am trying to build an application which requires glXDestroyPbuffer is this implemented? i get an undefined reference... i saw skip_index_glXDestroyPbuffer in src/proxy/config.h and disabled that, but it had no effect

**Comment by lunixbochs** [comment]
proxy is kinda a separate project - it's a way to use glshim through an emulation barrier like qemu. For the most part, I skip unimplemented functions in the generated proxy shim.

To support pbuffers, I'd probably need to play with wrapping it to `eglCreatePbufferSurface`. What's the program you're trying to build?

**Comment by krnlyng** [comment]
i am trying to build the EGL/GLES translator libraries from android which relies on glX: https://android.googlesource.com/platform/development/+/e387c21109bc363fa6fed30d8fa908fe073b6549/tools/emulator/opengl/host/libs/Translator/EGL/EglX11Api.cpp
this will hopefully someday allow me to pipe EGL/GLES calls from a android installation inside a chroot to a host renderer application. But i am only starting to learn EGL/GLES for this... any kind of help would be greatly appreciated :)

**Comment by lunixbochs** [comment]
Wait, why do you need glshim for this? Android is already using EGL/GLES, so doing EGL/GLES -> GLX/GL -> EGL/GLES is pretty gross.

**Comment by krnlyng** [comment]
as i have said, the Translator libraries use glx and i am not sure if i am experienced enough to rewrite them to use EGL directly, but yeah it would be pretty gross

**Comment by lunixbochs** [comment]
You should take a look at this: http://boards.openpandora.org/topic/17640-android-4450-oob/page-3

Apparently there's a way to use the host libraries directly from the emulator.

https://android.googlesource.com/platform/external/qemu/+/master/distrib/android-emugl/DESIGN

> The ability to use vendor-specific desktop EGL/GLES libraries is important. GPU vendors like NVidia, AMD or ARM all provide host versions of the EGL/GLES libraries that emulate their respectivie embedded graphics chipset. The renderer library can be configured to use these instead of the translator libraries provided with this project. This can be useful to more accurately emulate the behaviour of specific devices. Moreover, these vendor libraries typically expose vendor-specific extensions that are not provided by the translator libraries. We cannot expose them without modifying our code, but it's important to be able to do so without too much pain.

**Comment by krnlyng** [comment]
http://talk.maemo.org/showthread.php?p=1474082 here is my status, thanks for the thread, i will look at it

**Comment by krnlyng** [comment]
would you like to participate? basic communication, encoding, decoding, wayland window handling (X is disabled but can be reimplemented) and such works, but we could use help from EGL/GLES devs

**Comment by lunixbochs** [comment]
glshim can now facilitate remote rendering on its own. I'm closing this.
